// ============================================
// SISTEMA DE TRADUÇÃO - LAST POINT
// ============================================

const traducoes = {
    // ==========================================
    // IDIOMAS DISPONÍVEIS
    // ==========================================

    idiomas: {
        pt: 'Português',
        en: 'English'
    },


    // ==========================================
    // NAVBAR
    // ==========================================

    navbar: {
        pt: {
            inicio: 'Início',
            loja: 'Loja',
            regras: 'Regras',
            ajuda: 'Ajuda',
            discord: 'Discord',
            login: 'Login'
        },
        en: {
            inicio: 'Home',
            loja: 'Store',
            regras: 'Rules',
            ajuda: 'Help',
            discord: 'Discord',
            login: 'Login'
        }
    },


    // ==========================================
    // PÁGINA INICIAL
    // ==========================================

    index: {
        pt: {
            titulo: 'LAST POINT',
            subtitulo: 'Sobreviva. Construa. Conquiste.',
            descricao: 'O apocalipse zumbi mais realista do MTA.',
            bemVindo: 'Bem-vindo ao',
            jogar: 'Jogar Agora',
            verRegras: 'Ver Regras',
            jogadores: 'Jogadores',
            servidorAtivo: 'Servidor Ativo',
            avaliacoes: 'Avaliações',
            diferenciais: {
                antiCheat: 'Anti-Cheat',
                antiCheatDesc: 'Sistema avançado de proteção contra hackers e cheats.',
                equipe: 'Equipe Dedicada',
                equipeDesc: 'Administradores ativos 24 horas para garantir sua diversão.',
                conteudo: 'Conteúdo Exclusivo',
                conteudoDesc: 'Itens, eventos e sistemas únicos que você só encontra aqui.',
                comunidade: 'Comunidade Ativa',
                comunidadeDesc: 'Milhares de jogadores online para interagir e se divertir.'
            },
            comoJogar: {
                titulo: 'Como Jogar no',
                destaque: 'Last Point',
                passo1: 'Baixe o MTA',
                passo1Desc: 'Multi Theft Auto é o cliente necessário para jogar.',
                passo2: 'Conecte-se',
                passo2Desc: 'Use o IP do servidor e entre no mundo de Last Point.',
                passo3: 'Sobreviva',
                passo3Desc: 'Explore, construa e lute para sobreviver ao apocalipse.',
                ipServidor: 'IP do Servidor:',
                cagora: 'Comece Agora'
            },
            rodape: 'Todos os direitos reservados.'

        },
        en: {
            titulo: 'LAST POINT',
            subtitulo: 'Survive. Build. Conquer.',
            descricao: 'The most realistic zombie apocalypse in MTA.',
            bemVindo: 'Welcome to',
            jogar: 'Play Now',
            verRegras: 'View Rules',
            jogadores: 'Players',
            servidorAtivo: '24/7 Server',
            avaliacoes: 'Reviews',
            diferenciais: {
                antiCheat: 'Anti-Cheat',
                antiCheatDesc: 'Advanced protection system against hackers and cheats.',
                equipe: 'Dedicated Team',
                equipeDesc: 'Admins active 24/7 to ensure your fun.',
                conteudo: 'Exclusive Content',
                conteudoDesc: 'Unique items, events and systems you only find here.',
                comunidade: 'Active Community',
                comunidadeDesc: 'Thousands of players online to interact and have fun.'
            },
            comoJogar: {
                titulo: 'How to Play on',
                destaque: 'Last Point',
                passo1: 'Download MTA',
                passo1Desc: 'Multi Theft Auto is the client needed to play.',
                passo2: 'Connect',
                passo2Desc: 'Use the server IP and enter the world of Last Point.',
                passo3: 'Survive',
                passo3Desc: 'Explore, build and fight to survive the apocalypse.',
                ipServidor: 'Server IP:',
                cagora: 'Start now'
            },
            rodape: 'All rights reserved.'
        }
    },


    // ==========================================
    // PÁGINA DA LOJA
    // ==========================================

    loja: {
        pt: {
            titulo: 'Loja',
            subtitulo: 'Adquira benefícios exclusivos para sua jornada no mundo de Last Point.',
            produtos: {
                kit: {
                    nome: 'Kit Sobrevivente',
                    descricao: 'Equipamentos básicos para começar sua jornada em Last Point.',
                    preco: 'R$ 19,90'
                },
                vip: {
                    nome: 'VIP Survivor',
                    descricao: 'Benefícios exclusivos e vantagens dentro do servidor.',
                    preco: 'R$ 39,90',
                    badge: 'Mais Vendido'
                },
                elite: {
                    nome: 'VIP Elite',
                    descricao: 'O pacote definitivo para quem quer dominar Last Point.',
                    preco: 'R$ 69,90'
                },
                coins: {
                    nome: '1.000 Last Coins',
                    descricao: 'Moedas virtuais para utilizar na loja do servidor.',
                    preco: 'R$ 10,00'
                }
            },
            comprar: 'Comprar'
        },
        en: {
            titulo: 'Store',
            subtitulo: 'Get exclusive benefits for your journey in the world of Last Point.',
            produtos: {
                kit: {
                    nome: 'Survivor Kit',
                    descricao: 'Basic equipment to start your journey in Last Point.',
                    preco: '$3.99'
                },
                vip: {
                    nome: 'VIP Survivor',
                    descricao: 'Exclusive benefits and advantages within the server.',
                    preco: '$7.99',
                    badge: 'Best Seller'
                },
                elite: {
                    nome: 'VIP Elite',
                    descricao: 'The ultimate package for those who want to dominate Last Point.',
                    preco: '$13.99'
                },
                coins: {
                    nome: '1,000 Last Coins',
                    descricao: 'Virtual coins to use in the server store.',
                    preco: '$2.00'
                }
            },
            comprar: 'Buy'
        }
    },


// ==========================================
    // PÁGINA DE REGRAS
    // ==========================================

    regras: {
        pt: {
            titulo: 'Regras',
            subtitulo: 'Conheça as regras do servidor e mantenha uma boa experiência para todos os jogadores.',
            r1_titulo: 'Respeito aos jogadores',
            r1_desc: 'Respeite todos os jogadores e membros da equipe. Ofensas, preconceito, discriminação e perseguição não serão tolerados.',
            r2_titulo: 'Proibido Deathmatch',
            r2_desc: 'Não mate outros jogadores sem uma justificativa válida dentro do contexto do servidor. Toda ação deve possuir uma motivação coerente.',
            r3_titulo: 'Anti-RDM',
            r3_desc: 'É proibido atacar ou eliminar jogadores aleatoriamente sem qualquer interação ou motivo válido.',
            r4_titulo: 'Uso de veículos',
            r4_desc: 'Utilize os veículos de forma coerente. Não utilize veículos para atropelar jogadores propositalmente ou obter vantagens injustas.',
            r5_titulo: 'Exploração de bugs',
            r5_desc: 'É proibido utilizar bugs, falhas ou exploits para obter vantagens dentro do servidor. Bugs encontrados devem ser comunicados à administração.',
            r6_titulo: 'Cheats e programas externos',
            r6_desc: 'Qualquer tipo de cheat, hack, script ou programa que ofereça vantagem injusta é estritamente proibido.',
            r7_titulo: 'Uso do chat e voz',
            r7_desc: 'Utilize os canais de comunicação corretamente. Evite spam, flood, divulgação não autorizada e conteúdo ofensivo.',
            r8_titulo: 'Respeite a administração',
            r8_desc: 'As decisões da equipe devem ser respeitadas. Caso discorde de alguma decisão, procure a administração pelos canais oficiais.',
            atencao: {
                titulo: 'Atenção',
                descricao: 'O desconhecimento das regras não isenta o jogador de punições. As regras podem ser atualizadas a qualquer momento pela administração.'
            }
        },
        en: {
            titulo: 'Rules',
            subtitulo: 'Know the server rules and maintain a good experience for all players.',
            r1_titulo: 'Respect for players',
            r1_desc: 'Respect all players and staff members. Offenses, prejudice, discrimination, and harassment will not be tolerated.',
            r2_titulo: 'No Deathmatch',
            r2_desc: 'Do not kill other players without a valid justification within the context of the server. Every action must have a coherent motivation.',
            r3_titulo: 'Anti-RDM',
            r3_desc: 'It is forbidden to randomly attack or eliminate players without any interaction or valid reason.',
            r4_titulo: 'Vehicle usage',
            r4_desc: 'Use vehicles coherently. Do not use vehicles to intentionally run over players or gain unfair advantages.',
            r5_titulo: 'Bug exploitation',
            r5_desc: 'It is forbidden to use bugs, glitches, or exploits to gain advantages within the server. Any bugs found must be reported to the administration.',
            r6_titulo: 'Cheats and external programs',
            r6_desc: 'Any type of cheat, hack, script, or program that provides an unfair advantage is strictly prohibited.',
            r7_titulo: 'Chat and voice usage',
            r7_desc: 'Use communication channels properly. Avoid spam, flood, unauthorized advertising, and offensive content.',
            r8_titulo: 'Respect the administration',
            r8_desc: 'Staff decisions must be respected. If you disagree with a decision, contact the administration through official channels.',
            atencao: {
                titulo: 'Attention',
                descricao: 'Lack of knowledge of the rules does not exempt the player from punishments. Rules may be updated at any time by the administration.'
            }
        }
    },


    // ==========================================
    // PÁGINA DE AJUDA
    // ==========================================

// ==========================================
    // PÁGINA DE AJUDA
    // ==========================================

    ajuda: {
        pt: {
            titulo: 'Painel de Ajuda',
            subtitulo: 'Tire suas dúvidas e aprenda tudo sobre o mundo de Last Point.',
            cat1_titulo: 'Dicas Iniciais',
            cat1_qtd: '5 itens',
            q1_title: 'Dicas iniciais para sobreviver',
            q1_p1: '1. Priorize água e comida: Sua barra de fome e sede são essenciais. Procure por poços, rios e saqueie casas em busca de alimentos.',
            q1_p2: '2. Fique atento aos zumbis: Evite confrontos desnecessários no início. Use furtividade para se locomover.',
            q1_p3: '3. Junte-se a outros sobreviventes: Grupos aumentam suas chances de sobrevivência.',
            q1_p4: '4. Faça uma base simples: Comece com uma estrutura pequena para guardar seus itens.',
            q1_p5: '5. Explore com cuidado: Conheça o mapa e saiba onde encontrar recursos importantes.',
            q2_title: 'Como fazer uma base?',
            q2_p1: 'Para construir sua base, você precisará de madeira e pregos.',
            q2_li1: 'Colete madeira com um machado (F1 → Ferramentas).',
            q2_li2: 'Consiga pregos em caixas de ferramentas ou na recicladora.',
            q2_li3: 'Acesse o menu de construção (F2) e selecione "Construir Base".',
            q2_li4: 'Escolha o local e comece a montar sua estrutura.',
            q2_dica: '💡 Dica: Bases mais resistentes exigem materiais melhores como tijolos e cimento.',
            q3_title: 'Como raidar uma base?',
            q3_p1: 'Raidar uma base requer preparação e ferramentas adequadas:',
            q3_li1: 'Ferramentas de arrombamento: Marreta, pé de cabra ou explosivos.',
            q3_li2: 'Observe a estrutura: Identifique pontos fracos (portas, janelas).',
            q3_li3: 'Use explosivos: C4, granadas ou foguetes para paredes mais fortes.',
            q3_li4: 'Tenha um plano de fuga: Outros jogadores podem aparecer.',
            q3_aviso: '⚠️ Atenção: Raidar bases de outros jogadores tem regras específicas. Consulte as <a href="regras.html">Regras do Servidor</a>.',
            q4_title: 'Dia de raid - Como funciona?',
            q4_p1: 'O Dia de Raid é um evento especial onde as bases ficam vulneráveis em horários específicos.',
            q4_li1: 'Horários: Aos sábados das 14h às 18h (horário de Brasília).',
            q4_li2: 'Proteção: Durante os dias normais, as bases são protegidas.',
            q4_li3: 'Recompensas: Saques maiores e itens raros estão disponíveis.',
            q4_dica: '🎯 Estratégia: Planeje seus ataques e forme alianças para aumentar suas chances.',
            q5_title: 'Bases pagas - Como funcionam?',
            q5_p1: 'Bases pagas são áreas seguras adquiridas com Coins (moeda do servidor).',
            q5_li1: 'Proteção total: Nenhum jogador pode invadir sua base paga.',
            q5_li2: 'Armazenamento seguro: Seus itens ficam protegidos contra roubos.',
            q5_li3: 'Personalização: Você pode decorar e expandir sua base.',
            q5_li4: 'Valores: A partir de R$ 19,90 (consulte a <a href="loja.html">Loja</a>).',
            q5_dica: '💡 Vantagem: Ideal para quem quer jogar com tranquilidade sem perder seus itens.',

            cat2_titulo: 'Recursos e Coleta',
            cat2_qtd: '5 itens',
            q6_title: 'Como coletar madeira?',
            q6_p1: 'Para coletar madeira você precisa de um machado.',
            q6_li1: 'Acesse o menu F1 → Ferramentas e pegue um machado.',
            q6_li2: 'Encontre árvores pelo mapa (áreas verdes e florestas).',
            q6_li3: 'Com o machado em mãos, clique nas árvores para coletar.',
            q6_li4: 'Cada árvore rende de 5 a 15 unidades de madeira.',
            q6_dica: '💡 Dica: Use uma motosserra para coletar madeira mais rápido.',
            q7_title: 'Como coletar minérios?',
            q7_p1: 'Minérios são essenciais para fabricar itens avançados.',
            q7_li1: 'Pegue uma picareta no menu F1 → Ferramentas.',
            q7_li2: 'Encontre pedras e minas espalhadas pelo mapa.',
            q7_li3: 'Use a picareta para quebrar as rochas e coletar minérios.',
            q7_li4: 'Tipos de minério: Ferro, Cobre, Ouro, Titânio e Urânio.',
            q7_dica: '⚠️ Cuidado: Algumas áreas têm minérios mais raros, mas também mais perigosas.',
            q8_title: 'Como conseguir caixa de pregos?',
            q8_p1: 'Pregos são essenciais para construções e reparos.',
            q8_li1: 'Lojas: Compre em mercados e lojas pelo mapa.',
            q8_li2: 'Saque: Encontre em garagens, oficinas e construções abandonadas.',
            q8_li3: 'Reciclagem: Utilize a recicladora para transformar sucata em pregos.',
            q8_li4: 'Troca: Negocie com outros jogadores.',
            q8_dica: '💡 Dica: Caixas de ferramentas geralmente contêm pregos.',
            q9_title: 'Como conseguir graveto?',
            q9_p1: 'Gravetos são usados para fazer fogueiras e itens básicos.',
            q9_li1: 'Árvores caídas: Interaja com troncos no chão.',
            q9_li2: 'Arbustos: Alguns arbustos podem ser quebrados para gravetos.',
            q9_li3: 'Saque: Encontre em casas e construções abandonadas.',
            q9_li4: 'Ferramenta: Use uma faca ou machado para coletar mais rápido.',
            q10_title: 'Como fazer fogueira?',
            q10_p1: 'A fogueira é essencial para cozinhar e se aquecer.',
            q10_li1: 'Colete gravetos (veja item acima).',
            q10_li2: 'Acesse o menu de Fabricação (F3).',
            q10_li3: 'Selecione "Fogueira" e confirme.',
            q10_li4: 'Posicione a fogueira no chão e acenda com isqueiro ou fósforos.',
            q10_dica: '💡 Dica: Você pode cozinhar alimentos na fogueira.',

            cat3_titulo: 'Fabricação e Construção',
            cat3_qtd: '4 itens',
            q11_title: 'Como fazer mesa de trabalho?',
            q11_p1: 'A mesa de trabalho permite fabricar itens avançados.',
            q11_li1: 'Consiga madeira e pregos.',
            q11_li2: 'Acesse o menu de Fabricação (F3).',
            q11_li3: 'Selecione "Mesa de Trabalho" e confirme.',
            q11_li4: 'Posicione a mesa em sua base.',
            q11_dica: '💡 Benefício: Com a mesa você pode fazer armas, munição e equipamentos.',
            q12_title: 'Como fazer bandeira e suas funcionalidades?',
            q12_p1: 'A bandeira é o coração da sua base!',
            q12_h4_1: 'Como fazer:',
            q12_li1: 'Consiga tecido e madeira.',
            q12_li2: 'Use o menu Fabricação (F3).',
            q12_li3: 'Selecione "Bandeira" e confirme.',
            q12_h4_2: 'Funcionalidades:',
            q12_li4: 'Proteção de área: Cria uma zona segura ao redor.',
            q12_li5: 'Fast Travel: Permite teleporte para sua base (com tempo de espera).',
            q12_li6: 'Reviver companheiros: Membros do grupo podem ser revividos na bandeira.',
            q13_title: 'Como fazer tenda e caixas?',
            q13_p1: 'Tendas e caixas são usadas para armazenar seus itens.',
            q13_h4_1: 'Tenda:',
            q13_li1: 'Consiga lona e cordas.',
            q13_li2: 'Acesse Fabricação (F3) → Armazenamento.',
            q13_li3: 'Selecione "Tenda" e posicione.',
            q13_h4_2: 'Caixas:',
            q13_li4: 'Consiga madeira e pregos.',
            q13_li5: 'Acesse Fabricação (F3) → Armazenamento.',
            q13_li6: 'Selecione "Caixa" e posicione.',
            q13_dica: '💡 Dica: Caixas são mais seguras que tendas, mas exigem mais recursos.',
            q14_title: 'Como montar e reparar veículo?',
            q14_p1: 'Veículos são essenciais para explorar o mapa rapidamente.',
            q14_h4_1: 'Como montar:',
            q14_li1: 'Encontre as peças do veículo (motor, rodas, chassis).',
            q14_li2: 'Monte no menu F3 → Veículos.',
            q14_li3: 'Use combustível para abastecer.',
            q14_h4_2: 'Como reparar:',
            q14_li4: 'Use um kit de reparo ou ferramentas.',
            q14_li5: 'Acesse o veículo e selecione "Reparar".',
            q14_li6: 'Peças danificadas podem ser trocadas.',
            q14_dica: '⚠️ Atenção: Veículos fazem barulho e atraem zumbis!',

            cat4_titulo: 'Sobrevivência',
            cat4_qtd: '4 itens',
            q15_title: 'Como conseguir água?',
            q15_p1: 'Água é vital para sua sobrevivência.',
            q15_li1: 'Poços: Use um balde para coletar água.',
            q15_li2: 'Rios e lagos: Beba diretamente (risco de doenças).',
            q15_li3: 'Chuva: Coloque recipientes para coletar água da chuva.',
            q15_li4: 'Comida: Alguns alimentos fornecem hidratação.',
            q15_li5: 'Purificador: Use pastilhas ou ferva a água para purificar.',
            q15_dica: '💡 Dica: Sempre tenha uma garrafa de água reserva.',
            q16_title: 'Como conseguir comida?',
            q16_p1: 'Comida mantém sua energia e saúde.',
            q16_li1: 'Caça: Cace animais com armas ou armadilhas.',
            q16_li2: 'Coleta: Frutas, vegetais e cogumelos estão pelo mapa.',
            q16_li3: 'Saque: Encontre enlatados em casas e mercados.',
            q16_li4: 'Pesca: Use uma vara de pescar em rios e lagos.',
            q16_li5: 'Agricultura: Plante sementes e cultive alimentos.',
            q16_dica: '⚠️ Cuidado: Comida crua pode causar doenças. Cozinhe antes de comer.',
            q17_title: 'Como curar doenças?',
            q17_p1: 'Doenças podem ser fatais se não tratadas.',
            q17_h4_1: 'Tipos de doenças:',
            q17_li1: 'Infecção: Causada por feridas não tratadas.',
            q17_li2: 'Envenenamento: Comida estragada ou água contaminada.',
            q17_li3: 'Hipotermia: Ficar muito tempo no frio.',
            q17_li4: 'Insolação: Exposição excessiva ao sol.',
            q17_h4_2: 'Remédios:',
            q17_li5: 'Antibióticos: Curam infecções.',
            q17_li6: 'Carvão ativado: Trata envenenamento.',
            q17_li7: 'Remédios: Encontre em hospitais e farmácias.',
            q17_li8: 'Ervas medicinais: Coletadas na natureza.',
            q17_dica: '💡 Dica: Previna-se mantendo alimentação e hidratação em dia.',
            q18_title: 'Como funciona a recicladora?',
            q18_p1: 'A recicladora transforma itens inúteis em recursos valiosos.',
            q18_li1: 'Construa a recicladora no menu F3 → Construção.',
            q18_li2: 'Coloque itens que você não usa (roupas, latas, sucata).',
            q18_li3: 'A recicladora processa e gera materiais como:',
            q18_subli1: 'Tecido (de roupas)',
            q18_subli2: 'Metal (de ferramentas)',
            q18_subli3: 'Plástico (de garrafas)',
            q18_subli4: 'Pregos (de sucata)',
            q18_dica: '💡 Dica: Use a recicladora para aproveitar ao máximo seus recursos.',

            cat5_titulo: 'Militar e Avançado',
            cat5_qtd: '4 itens',
            q19_title: 'Sobre as Military Bases',
            q19_p1: 'As Military Bases são áreas de alto risco e alta recompensa.',
            q19_li1: 'Localização: Áreas estratégicas do mapa (consulte o mapa do servidor).',
            q19_li2: 'Itens encontrados: Armas militares, munição, coletes, equipamentos táticos.',
            q19_li3: 'Perigos: Zumbis mais fortes, outros jogadores e radiação.',
            q19_li4: 'Horário: Algumas bases são limpas em horários específicos.',
            q19_aviso: '⚠️ Atenção: Bases militares são PvP ativo. Prepare-se para combate.',
            q19_dica: '💡 Dica: Vá em grupo e leve suprimentos extras.',
            q20_title: 'Como fazer pólvora?',
            q20_p1: 'A pólvora é essencial para fabricar munição e explosivos.',
            q20_li1: 'Consiga carvão (queime madeira na fogueira).',
            q20_li2: 'Consiga enxofre (minere em vulcões ou áreas específicas).',
            q20_li3: 'Consiga salitre (encontre em cavernas ou recicle).',
            q20_li4: 'Use a Mesa de Trabalho e selecione "Fabricar Pólvora".',
            q20_dica: '💡 Dica: A pólvora também pode ser encontrada em bases militares.',
            q21_title: 'Como fazer componentes eletrônicos?',
            q21_p1: 'Componentes eletrônicos são usados para itens avançados.',
            q21_li1: 'Consiga cobre e silício.',
            q21_li2: 'Derreta o cobre para fazer fios.',
            q21_li3: 'Combine fios com silício na Mesa de Trabalho.',
            q21_li4: 'Selecione "Componentes Eletrônicos".',
            q21_dica: '💡 Uso: Essenciais para rádios, sistemas de segurança e veículos avançados.',
            q22_title: 'Sobre os painéis F1, F2, F3 e F4',
            q22_p1: 'Os painéis de atalho são essenciais para navegar rapidamente:',
            q22_f1_t: 'Inventário e Ferramentas',
            q22_f1_d: 'Acesse seu inventário, equipamentos e ferramentas básicas.',
            q22_f2_t: 'Construção e Base',
            q22_f2_d: 'Construa estruturas, posicione itens e gerencie sua base.',
            q22_f3_t: 'Fabricação',
            q22_f3_d: 'Fabrique armas, munição, equipamentos e itens avançados.',
            q22_f4_t: 'Menu do Servidor',
            q22_f4_d: 'Acesse informações do servidor, grupos e configurações.',
            q22_dica: '💡 Dica: Memorize os atalhos para agir mais rápido em situações de perigo.',

            cat6_titulo: 'Configuração',
            cat6_qtd: '1 item',
            q23_title: 'Como fazer whitelist?',
            q23_p1: 'A whitelist permite que apenas jogadores autorizados entrem no servidor.',
            q23_h4_1: 'Para jogadores:',
            q23_li1: 'Acesse o Discord oficial do servidor.',
            q23_li2: 'Entre no canal #whitelist.',
            q23_li3: 'Envie seu Nickname e ID do Steam/MTA.',
            q23_li4: 'Aguarde a aprovação da administração.',
            q23_h4_2: 'Para administradores:',
            q23_li5: 'Acesse o Painel Admin (F4).',
            q23_li6: 'Selecione "Gerenciar Whitelist".',
            q23_li7: 'Adicione ou remova jogadores da lista.',
            q23_aviso: '⚠️ Atenção: A whitelist é obrigatória para jogar no servidor.'
        },
        en: {
            titulo: 'Help Panel',
            subtitulo: 'Get your questions answered and learn everything about the world of Last Point.',
            cat1_titulo: 'Initial Tips',
            cat1_qtd: '5 items',
            q1_title: 'Initial survival tips',
            q1_p1: '1. Prioritize water and food: Your hunger and thirst bars are essential. Look for wells, rivers, and loot houses for food.',
            q1_p2: '2. Watch out for zombies: Avoid unnecessary confrontations at the start. Use stealth to move around.',
            q1_p3: '3. Team up with other survivors: Groups increase your chances of survival.',
            q1_p4: '4. Build a simple base: Start with a small structure to store your items.',
            q1_p5: '5. Explore carefully: Know the map and learn where to find key resources.',
            q2_title: 'How to build a base?',
            q2_p1: 'To build your base, you will need wood and nails.',
            q2_li1: 'Gather wood with an axe (F1 → Tools).',
            q2_li2: 'Get nails from toolboxes or the recycler.',
            q2_li3: 'Access the building menu (F2) and select "Build Base".',
            q2_li4: 'Choose the location and start assembling your structure.',
            q2_dica: '💡 Tip: Sturdier bases require better materials like bricks and cement.',
            q3_title: 'How to raid a base?',
            q3_p1: 'Raiding a base requires preparation and proper tools:',
            q3_li1: 'Breaching tools: Sledgehammer, crowbar, or explosives.',
            q3_li2: 'Observe the structure: Identify weak spots (doors, windows).',
            q3_li3: 'Use explosives: C4, grenades, or rockets for stronger walls.',
            q3_li4: 'Have an escape plan: Other players may show up.',
            q3_aviso: '⚠️ Attention: Raiding other players\' bases has specific rules. Check the <a href="regras.html">Server Rules</a>.',
            q4_title: 'Raid Day - How does it work?',
            q4_p1: 'Raid Day is a special event where bases become vulnerable at specific times.',
            q4_li1: 'Schedule: Saturdays from 2:00 PM to 6:00 PM (BRT).',
            q4_li2: 'Protection: On normal days, bases are protected.',
            q4_li3: 'Rewards: Bigger loot and rare items are available.',
            q4_dica: '🎯 Strategy: Plan your attacks and form alliances to increase your chances.',
            q5_title: 'Paid bases - How do they work?',
            q5_p1: 'Paid bases are safe areas purchased with Coins (server currency).',
            q5_li1: 'Total protection: No player can raid your paid base.',
            q5_li2: 'Safe storage: Your items are protected against theft.',
            q5_li3: 'Customization: You can decorate and expand your base.',
            q5_li4: 'Pricing: Starting from $3.99 / R$ 19,90 (check the <a href="loja.html">Store</a>).',
            q5_dica: '💡 Advantage: Ideal for those who want to play peacefully without losing their items.',

            cat2_titulo: 'Resources and Gathering',
            cat2_qtd: '5 items',
            q6_title: 'How to gather wood?',
            q6_p1: 'To gather wood you need an axe.',
            q6_li1: 'Access the menu F1 → Tools and grab an axe.',
            q6_li2: 'Find trees across the map (green areas and forests).',
            q6_li3: 'With the axe equipped, click on trees to gather.',
            q6_li4: 'Each tree yields 5 to 15 units of wood.',
            q6_dica: '💡 Tip: Use a chainsaw to gather wood faster.',
            q7_title: 'How to mine ores?',
            q7_p1: 'Ores are essential for crafting advanced items.',
            q7_li1: 'Get a pickaxe in the F1 → Tools menu.',
            q7_li2: 'Find rocks and mines scattered across the map.',
            q7_li3: 'Use the pickaxe to break rocks and collect ores.',
            q7_li4: 'Types of ore: Iron, Copper, Gold, Titanium, and Uranium.',
            q7_dica: '⚠️ Caution: Some areas have rarer ores, but are also more dangerous.',
            q8_title: 'How to get a box of nails?',
            q8_p1: 'Nails are essential for building and repairs.',
            q8_li1: 'Shops: Buy at markets and stores around the map.',
            q8_li2: 'Loot: Find in garages, workshops, and abandoned buildings.',
            q8_li3: 'Recycling: Use the recycler to turn scrap into nails.',
            q8_li4: 'Trade: Trade with other players.',
            q8_dica: '💡 Tip: Toolboxes usually contain nails.',
            q9_title: 'How to get sticks?',
            q9_p1: 'Sticks are used to craft campfires and basic items.',
            q9_li1: 'Fallen trees: Interact with logs on the ground.',
            q9_li2: 'Bushes: Some bushes can be broken for sticks.',
            q9_li3: 'Loot: Find in houses and abandoned structures.',
            q9_li4: 'Tool: Use a knife or axe to gather faster.',
            q10_title: 'How to make a campfire?',
            q10_p1: 'A campfire is essential for cooking and staying warm.',
            q10_li1: 'Gather sticks (see item above).',
            q10_li2: 'Access the Crafting menu (F3).',
            q10_li3: 'Select "Campfire" and confirm.',
            q10_li4: 'Place the campfire on the ground and light it with a lighter or matches.',
            q10_dica: '💡 Tip: You can cook food on the campfire.',

            cat3_titulo: 'Crafting and Building',
            cat3_qtd: '4 items',
            q11_title: 'How to make a workbench?',
            q11_p1: 'The workbench allows you to craft advanced items.',
            q11_li1: 'Get wood and nails.',
            q11_li2: 'Access the Crafting menu (F3).',
            q11_li3: 'Select "Workbench" and confirm.',
            q11_li4: 'Place the workbench in your base.',
            q11_dica: '💡 Benefit: With the workbench you can craft weapons, ammo, and equipment.',
            q12_title: 'How to make a flag and its features?',
            q12_p1: 'The flag is the heart of your base!',
            q12_h4_1: 'How to make:',
            q12_li1: 'Get cloth and wood.',
            q12_li2: 'Use the Crafting menu (F3).',
            q12_li3: 'Select "Flag" and confirm.',
            q12_h4_2: 'Features:',
            q12_li4: 'Area protection: Creates a safe zone around it.',
            q12_li5: 'Fast Travel: Allows teleporting to your base (cooldown applies).',
            q12_li6: 'Revive teammates: Group members can be revived at the flag.',
            q13_title: 'How to make tents and storage boxes?',
            q13_p1: 'Tents and boxes are used to store your items.',
            q13_h4_1: 'Tent:',
            q13_li1: 'Get tarp and ropes.',
            q13_li2: 'Access Crafting (F3) → Storage.',
            q13_li3: 'Select "Tent" and place it.',
            q13_h4_2: 'Boxes:',
            q13_li4: 'Get wood and nails.',
            q13_li5: 'Access Crafting (F3) → Storage.',
            q13_li6: 'Select "Box" and place it.',
            q13_dica: '💡 Tip: Boxes are safer than tents, but require more resources.',
            q14_title: 'How to assemble and repair a vehicle?',
            q14_p1: 'Vehicles are essential for exploring the map quickly.',
            q14_h4_1: 'How to assemble:',
            q14_li1: 'Find vehicle parts (engine, wheels, chassis).',
            q14_li2: 'Assemble in the F3 → Vehicles menu.',
            q14_li3: 'Use fuel to refuel.',
            q14_h4_2: 'How to repair:',
            q14_li4: 'Use a repair kit or tools.',
            q14_li5: 'Interact with the vehicle and select "Repair".',
            q14_li6: 'Damaged parts can be replaced.',
            q14_dica: '⚠️ Attention: Vehicles make noise and attract zombies!',

            cat4_titulo: 'Survival',
            cat4_qtd: '4 items',
            q15_title: 'How to get water?',
            q15_p1: 'Water is vital for your survival.',
            q15_li1: 'Wells: Use a bucket to collect water.',
            q15_li2: 'Rivers and lakes: Drink directly (risk of disease).',
            q15_li3: 'Rain: Place containers to collect rainwater.',
            q15_li4: 'Food: Some food items provide hydration.',
            q15_li5: 'Purifier: Use tablets or boil water to purify.',
            q15_dica: '💡 Tip: Always keep a backup water bottle.',
            q16_title: 'How to get food?',
            q16_p1: 'Food keeps your energy and health up.',
            q16_li1: 'Hunting: Hunt animals using weapons or traps.',
            q16_li2: 'Foraging: Fruits, vegetables, and mushrooms are across the map.',
            q16_li3: 'Looting: Find canned food in houses and markets.',
            q16_li4: 'Fishing: Use a fishing rod in rivers and lakes.',
            q16_li5: 'Farming: Plant seeds and grow crops.',
            q16_dica: '⚠️ Caution: Raw food can cause disease. Cook before eating.',
            q17_title: 'How to cure diseases?',
            q17_p1: 'Diseases can be fatal if left untreated.',
            q17_h4_1: 'Types of diseases:',
            q17_li1: 'Infection: Caused by untreated wounds.',
            q17_li2: 'Poisoning: Spoiled food or contaminated water.',
            q17_li3: 'Hypothermia: Staying in the cold for too long.',
            q17_li4: 'Heatstroke: Excessive sun exposure.',
            q17_h4_2: 'Treatments:',
            q17_li5: 'Antibiotics: Cure infections.',
            q17_li6: 'Activated charcoal: Treats poisoning.',
            q17_li7: 'Medicine: Find in hospitals and pharmacies.',
            q17_li8: 'Medicinal herbs: Gathered in nature.',
            q17_dica: '💡 Tip: Prevent illness by keeping up with food and hydration.',
            q18_title: 'How does the recycler work?',
            q18_p1: 'The recycler transforms useless items into valuable resources.',
            q18_li1: 'Build the recycler in the menu F3 → Building.',
            q18_li2: 'Place unused items inside (clothes, cans, scrap).',
            q18_li3: 'The recycler processes and generates materials such as:',
            q18_subli1: 'Cloth (from clothes)',
            q18_subli2: 'Metal (from tools)',
            q18_subli3: 'Plastic (from bottles)',
            q18_subli4: 'Nails (from scrap)',
            q18_dica: '💡 Tip: Use the recycler to make the most of your resources.',

            cat5_titulo: 'Military and Advanced',
            cat5_qtd: '4 items',
            q19_title: 'About Military Bases',
            q19_p1: 'Military Bases are high-risk, high-reward areas.',
            q19_li1: 'Location: Strategic areas of the map (check server map).',
            q19_li2: 'Loot: Military weapons, ammo, body armor, tactical gear.',
            q19_li3: 'Dangers: Stronger zombies, other players, and radiation.',
            q19_li4: 'Schedule: Some bases reset at specific times.',
            q19_aviso: '⚠️ Attention: Military bases are active PvP zones. Prepare for combat.',
            q19_dica: '💡 Tip: Go in a group and bring extra supplies.',
            q20_title: 'How to craft gunpowder?',
            q20_p1: 'Gunpowder is essential for crafting ammo and explosives.',
            q20_li1: 'Get charcoal (burn wood in the campfire).',
            q20_li2: 'Get sulfur (mine in volcanoes or specific areas).',
            q20_li3: 'Get saltpeter (find in caves or recycle).',
            q20_li4: 'Use the Workbench and select "Craft Gunpowder".',
            q20_dica: '💡 Tip: Gunpowder can also be found at military bases.',
            q21_title: 'How to craft electronic components?',
            q21_p1: 'Electronic components are used for advanced items.',
            q21_li1: 'Get copper and silicon.',
            q21_li2: 'Melt copper to make wires.',
            q21_li3: 'Combine wires with silicon at the Workbench.',
            q21_li4: 'Select "Electronic Components".',
            q21_dica: '💡 Usage: Essential for radios, security systems, and advanced vehicles.',
            q22_title: 'About F1, F2, F3, and F4 panels',
            q22_p1: 'Shortcut panels are essential for quick navigation:',
            q22_f1_t: 'Inventory and Tools',
            q22_f1_d: 'Access your inventory, equipment, and basic tools.',
            q22_f2_t: 'Building and Base',
            q22_f2_d: 'Build structures, place items, and manage your base.',
            q22_f3_t: 'Crafting',
            q22_f3_d: 'Craft weapons, ammo, equipment, and advanced items.',
            q22_f4_t: 'Server Menu',
            q22_f4_d: 'Access server information, groups, and settings.',
            q22_dica: '💡 Tip: Memorize shortcuts to act faster in dangerous situations.',

            cat6_titulo: 'Configuration',
            cat6_qtd: '1 item',
            q23_title: 'How to get whitelisted?',
            q23_p1: 'The whitelist ensures only authorized players can join the server.',
            q23_h4_1: 'For players:',
            q23_li1: 'Access the official Discord server.',
            q23_li2: 'Enter the #whitelist channel.',
            q23_li3: 'Send your Nickname and Steam/MTA ID.',
            q23_li4: 'Wait for administration approval.',
            q23_h4_2: 'For administrators:',
            q23_li5: 'Access the Admin Panel (F4).',
            q23_li6: 'Select "Manage Whitelist".',
            q23_li7: 'Add or remove players from the list.',
            q23_aviso: '⚠️ Attention: Whitelist is mandatory to play on the server.'
        }
    }
};

// Verifica se o objeto foi carregado corretamente
console.log('✅ Traduções carregadas:', Object.keys(traducoes));